server:
  port: 8082
  servlet:
    context-path: /sso-server
spring:
  application:
    name: sso-server
  profiles:
    active: dev
  mvc:
    async:
      request-timeout: 30000
logging:
  config: classpath:log4j2.yml



